import { useState } from 'react'
import SearchableList from '../components/SearchableList'

const MORPHS_DATA = [
  {
    id: 1,
    name: 'Flats',
    type: 'Biomorph',
    description: 'Flats are baseline unmodified humans, born with all of the natural defects',
    details: 'Flats are baseline unmodified humans, born with all of the natural defects, hereditary diseases, and other genetic mutations that evolution so lovingly applies. Flats are increasingly rare—most died off with the rest of humanity during the Fall. Most new children are splicers—screened and genefixed at the least—except in habitats where flats are treated as second-class citizens and indentured labor.',
    implants: 'None',
    aptitude_max: '20',
    durability: '30',
    wound_threshold: '6',
    advantages: '',
    disadvantages: 'None (Genetic Defects trait common)',
    cp_cost: '0',
    credit_cost: 'High',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 2,
    name: 'Splicers',
    type: 'Biomorph',
    description: 'Splicers are genefixed humans.',
    details: 'Splicers are genefixed humans. Their genome has been cleansed of hereditary diseases and optimized for looks and health, but has not otherwise been substantially upgraded. Splicers make up the majority of transhumanity.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '10',
    credit_cost: 'High',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 3,
    name: 'Exalts',
    type: 'Biomorph',
    description: 'Exalt morphs are genetically enhanced humans',
    details: 'Exalt morphs are genetically enhanced humans, designed to emphasize specific traits. Their genetic code has been tweaked to make them healthier, smarter, and more attractive. Their metabolism is modified to predispose them towards staying fit and athletic for the duration of an extended lifespan.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COG, +5 to three other aptitudes of the player\'s choice',
    disadvantages: '',
    cp_cost: '30',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 4,
    name: 'Mentons',
    type: 'Biomorph',
    description: 'Mentons are genetically modified to increase cognitive abilities',
    details: 'Mentons are genetically modified to increase cognitive abilities, particularly learning ability, creativity, attentiveness, and memory. Rumors exist of super- enhanced mentons with more extreme intelligence mods, but brain-hacking is notoriously difficult, and many attempts to redesign mental faculties result in impaired functioning, instability, or insanity.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Eidetic Memory, Hyper Linguist, Math Boost',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+10 COG, +5 INT, +5 WIL, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 5,
    name: 'Olympians',
    type: 'Biomorph',
    description: 'Olympians are human upgrades with improved athletic capabilities',
    details: 'Olympians are human upgrades with improved athletic capabilities like endurance, eye-hand coordination, and cardiovascular functions. Olympians are common among athletes, dancers, freerunners, and soldiers.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +5 REF, +10 SOM, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[
      {
        id: 1,
        name: 'Titanian Olympians',
        details: 'Often used by athletes and outdoor workers, these are standard olympian biomorphs augmented with temperature tolerance (improved cold). CP and Credit Costs remain the same.'
      },
    ],
  },
  {
    id: 6,
    name: 'Slyphs',
    type: 'Biomorph',
    description: 'Slyph morphs are tailor-made for media icons',
    details: 'Slyph morphs are tailor-made for media icons, elite socialites, XP stars, models, and narcissists. Slyph gene sequences are specifically designed for distinctive good looks. Ethereal and elfin features are common, with slim and lithe bodies. Their metabolism has also been sanitized to eliminate unpleasant bodily odors and their pheromones adjusted for universal appeal.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Enhanced Pheromones',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Striking Looks (Level 1) trait, +5 COO, +10 SAV, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 7,
    name: 'Bouncers',
    type: 'Biomorph',
    description: 'Bouncers are humans genetically adapted for zero-g',
    details: 'Bouncers are humans genetically adapted for zero-g and microgravity environments. Their legs are more limber, and their feet can grasp as well as their hands.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Grip Pads, Oxygen Reserve, Prehensile Feet',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Limber (Level 1) trait, +5 COO, +5 SOM, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 8,
    name: 'Furies',
    type: 'Biomorph',
    description: 'Furies are combat morphs.',
    details: 'Furies are combat morphs. These transgenic human upgrades feature genetics tailored for endurance, strength, and reflexes, as well as behavioral modifications for aggressiveness and cunning. To offset tendencies for unruliness and macho behavior patterns, furies feature gene sequences promoting pack mentalities and cooperation, and they tend to be biologically female.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Bioweave Armor (Light), Cortical Stack, Enhanced Vision, Neurachem (Level 1), Toxin Filters',
    aptitude_max: '30',
    durability: '50',
    wound_threshold: '10',
    advantages: '+5 COO, +5 REF, +10 SOM, +5 WIL, +5 to one aptitude of the player\'s choice.',
    disadvantages: '',
    cp_cost: '75',
    credit_cost: 'Expensive (minimum 40,000)',
    mobility: 'Feet 4/20',
    speed: '1 + 1 (neurachem)',
    variants:[],
  },
  {
    id: 9,
    name: 'Futuras',
    type: 'Biomorph',
    description: 'An exalt variant, futura morphs were specially crafted for the “Lost generation.”',
    details: 'An exalt variant, futura morphs were specially crafted for the “Lost generation.” Tailor-made for accelerated growth and adjusted for confidence, self-reliance, and adaptability, futuras were intended to help transhumanity regain its foothold. These programs proved disastrous and the line was discontinued, but some models remain, viewed by some with distaste and others as collectibles or exotic oddities.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Eidetic Memory, Emotional Dampers',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COG, +5 SAV, +10 WIL, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive (exceptionally rare; 50,000+)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 10,
    name: 'Ghosts',
    type: 'Biomorph',
    description: 'Ghosts are partially designed for combat applications, but their primary focus is stealth and infiltration.',
    details: 'Ghosts are partially designed for combat applications, but their primary focus is stealth and infiltration. Their genetic profile encourages speed, agility, and reflexes, and their minds are modified for patience and problem-solving.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Adrenal Boost, Enhanced Vision, Grip Pads',
    aptitude_max: '30',
    durability: '45',
    wound_threshold: '9',
    advantages: '+10 COO, +5 REF, +5 SOM, +5 WIL, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 11,
    name: 'Hibernoids',
    type: 'Biomorph',
    description: 'Hibernoids are transgenic-modified humans with heavily altered sleep patterns and metabolic processes.',
    details: 'Hibernoids are transgenic-modified humans with heavily altered sleep patterns and metabolic processes. Hibernoids have a decreased need for sleep, requiring only 1–2 hours a day on average. They also have the ability to trigger a form of voluntary hibernation, effectively stopping their metabolism and need for oxygen. Hibernoids make excellent long-duration space travelers and habtechs, but these morphs are also favored by personal aides and hypercapitalists with non-stop lifestyles.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Circadian Regulation, Cortical Stack, Hibernation',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 INT, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 12,
    name: 'Neotenics',
    type: 'Biomorph',
    description: 'Neotenics are transhumans modified to retain a child-like form.',
    details: 'Neotenics are transhumans modified to retain a child-like form. They are smaller, more agile, inquisitive, and less resource-depleting, making them ideal for habitat living and spacecraft. Some people find neotenic sleeves distasteful, especially when employed in certain media and sex work capacities.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '20 (SOM), 30 (all else)',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 COO, +5 INT, +5 REF, +5 to one aptitude of the player\'s choice; neotenics count as a small target (-10 modifier to hit in combat)',
    disadvantages: 'Social Stigma (Neotenic) trait',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 13,
    name: 'Remade',
    type: 'Biomorph',
    description: 'The remade are completely redesigned humans: humans 2.0.',
    details: 'The remade are completely redesigned humans: humans 2.0. Their cardiovascular systems are stronger, the digestive tract has been sanitized and restructured to eliminate flaws, and they have otherwise been optimized for good health, smarts, and longevity with numerous transgenic mods. The remade are popular with the ultimates faction. The remade look close to human, but are different in very noticeable and sometimes eerie ways: taller, lack of hair, slightly larger craniums, wider eyes, smaller noses, smaller teeth, and elongated digits.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Circadian Regulation, Clean Metabolism, Cortical Stack, Eidetic Memory, Enhanced Respiration, Temperature Tolerance, Toxin Filters',
    aptitude_max: '40',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 COG, +5 SAV, +10 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: 'Uncanny Valley trait',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 14,
    name: 'Rusters',
    type: 'Biomorph',
    description: 'Adapted for survival with minimum gear in the not-yet-terraformed Martian environment',
    details: 'Adapted for survival with minimum gear in the not-yet-terraformed Martian environment, these transgenic morphs feature insulated skin for more effective thermoregulation and respiratory system improvements to require less oxygen and filter carbon dioxyde, among other mods.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Enhanced Respiration, Temperature Tolerance',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 SOM, +5 to one aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 15,
    name: 'Neo-Avians',
    type: 'Biomorph',
    description: 'Neo-avians include ravens, crows, and gray parrots uplifted to human-level intelligence.',
    details: 'Neo-avians include ravens, crows, and gray parrots uplifted to human-level intelligence. Their physical sizes are much larger than their non-uplifted cousins (to the size of a human child), with larger heads for their increased brain size. Numerous transgenic modifica- tions have been made to their wings, allowing them to retain limited flight capabilities at 1 g, but giving them a more bat-like physiology so they can bend and fold better and adding primitive digits for basic tool manipulation. Their toes are also more articulated and now accompanied with an opposable thumb. Neo-avians have adapted well to microgravity environments, and are favored for their small size and reduced resource use.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '25 (20 SOM)',
    durability: '20',
    wound_threshold: '4',
    advantages: 'Beak/Claw Attack (1d10 DV, -1, use Unarmed Combat skill), Flight, +5 INT, +10 REF, +5 to one other aptitude of the player’s choice. Neo-avians count as a small target (-10 modifier to hit in combat).',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Winged 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 16,
    name: 'Neo-Hominids',
    type: 'Biomorph',
    description: 'Neo-hominids are uplifted chimpanzees, gorillas, and orangutans.',
    details: 'Neo-hominids are uplifted chimpanzees, gorillas, and orangutans. All feature enhanced intelligence and bipedal frames.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Prehensile Feet',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 COO, +5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +10 Climbing skill',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 17,
    name: 'Octomorphs',
    type: 'Biomorph',
    description: '',
    details: 'These uplifted octopi sleeves have proven quite useful in zero-gravity environments. They retain eight arms, their chameleon ability to change skin color, ink sacs, and a sharp beak. They also have increased brain mass and longevity, can breathe both air and water, and lack a skeletal structure so they can squeeze through tight spaces. Octomorphs typically crawl along in zero gravity using their arm suckers and expelling air for propulsion and can even walk on two of their arms in low gravity. Their eyes have been enhanced with color vision, provide a 360-degree field of vision, and rotationally adjust to keep the slit-shaped pupil aligned with “up.” A transgenic vocal system allows them to speak.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Chameleon Skin',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '8 Arms, Beak Attack (1d10 DV, AP -1, use Unarmed Combat skill), Ink Attack (blinding, use Exotic Ranged: Ink Attack skill), Limber (Level 2) trait, 360-degree Vision, +30 Swimming skill, +10 Climbing skill, +5 COO, +5 INT, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '50',
    credit_cost: 'Expensive (minimum 30,000+)',
    mobility: 'Tenticles 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 18,
    name: 'Pleasure Pods',
    type: 'Pods',
    description: 'Pleasure pods are exactly what they seem: faux humans designed purely for intimate entertainment purposes.',
    details: 'Pleasure pods are exactly what they seem: faux humans designed purely for intimate entertainment purposes. Pleasure pods have extra nerve clusters in their erogenous zones, fine motor control over certain muscle groups, enhanced pheromones, sanitized metabolisms, and the genetics for purring. Naturally, they are crafted for good looks and charisma and enhanced in other areas as well. Pleasure pods are capable of switching their sex at will to male, female, hermaphrodite, neuter, or other intersex variations.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Cyberbrain, Enhanced Pheromones, Mnemonic Augmentation, Puppet Sock, Sex Switch',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 INT, +5 SAV, +5 to one aptitude of the player’s choice',
    disadvantages: 'Social Stigma (Pleasure Pod) trait',
    cp_cost: '20',
    credit_cost: 'High',
    mobility: 'Walker 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 19,
    name: 'Worker Pods',
    type: 'Pods',
    description: 'Part exalt human, part machine',
    details: 'Part exalt human, part machine, these basic pods are virtually indistinguishable from humans. Worker pods are often used in menial labor jobs where interaction with humans is necessary.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Puppet Sock',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+10 SOM, +5 to one aptitude of the player’s choice',
    disadvantages: 'Social Stigma (Pod) trait',
    cp_cost: '20',
    credit_cost: 'High',
    mobility: 'Walker 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 20,
    name: 'Novacrab',
    type: 'Pods',
    description: 'Novacrabs are a pod design bioengineered from coconut crab and spider crab stock',
    details: 'Novacrabs are a pod design bioengineered from coconut crab and spider crab stock and grown to a larger (human) size. Novacrabs are ideal for hazardous work environments as well as vacworker, police, or bodyguard duties, given their ten 2-meter long legs, massive claws, and chitinous armor. They climb and handle microgravity well and can withstand a wide range of atmospheric pressure (and sudden pressure changes) from vacuum to deep sea. Novacrabs feature compound eyes (with human-equivalent image resolution), gills, dexterous manipulatory digits on their fifth set of limbs, and transgenic vocal cords.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Carapace Armor, Cortical Stack, Cyberbrain, Enhanced Respiration, Gills, Mnemonic Augmentation, Oxygen Reserve, Puppet Sock, Temperature Tolerance, Vacuum Sealing',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '10 legs, Carapace Armor (11/11), Claw Attack (DV 2d10), +10 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: '',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 30,000+)',
    mobility: 'Walker 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 21,
    name: 'Case',
    type: 'Synthetic Morph',
    description: 'Cases are extremely cheap, mass-produced robotic shells',
    details: 'Cases are extremely cheap, mass-produced robotic shells intended to provide an affordable remorphing option for the millions of infugees created by the Fall. Though many varieties of case shells exist, they are uniformly regarded as shoddy and inferior. Most case morphs are vaguely anthropomorphic, with a thin framework body standing just shorter than an average human. They suffer from frequent malfunctions.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation',
    aptitude_max: '20',
    durability: '20',
    wound_threshold: '4',
    advantages: 'Armor (4/4)',
    disadvantages: '–5 to one chosen aptitude, Lemon trait, Social Stigma (Clanking Masses) trait',
    cp_cost: '5',
    credit_cost: 'Moderate',
    mobility: 'Walker 4/16',
    speed: '1',
    variants:[],
  },
  {
    id: 22,
    name: 'Cetus',
    type: 'Synthetic Morph',
    description: 'The cetus, named after a mythological sea monster, was designed for deep sea activity',
    details: 'The cetus, named after a mythological sea monster, was designed for deep sea activity and is capable of operating under extreme pressure and cold. It is a favored morph for use in the undersea domains of Ceres and Europa. Capable of moving quickly underwater, the morph can also operate outside of water in the atmospheric portion of habitats. Cetus morphs are slightly smaller than arachnoids',
    implants: 'Access Jacks, Basic Mesh Inserts, Chemical Sniffer, Cortical Stack, Cyberbrain, Direction Sense, Echolocation, Enhanced Hearing, Enhanced Vision, Extra Limbs (8), Headlights, Hydrostatic Pressure Adaptation',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '8 Limbs, +5 COO, +5 SOM, +5 to one other aptitude of the player’s choice, Armor 8/8',
    disadvantages: '',
    cp_cost: '45',
    credit_cost: 'Expensive',
    mobility: 'Walker 4/20, Submarine 4/36)',
    speed:'1',
    variants:[],
  },
  {
    id: 23,
    name: 'Synth',
    type: 'Synthetic Morph',
    description: 'Synths are anthropomorphic robotic shells (androids and gynoids).',
    details: 'Synths are anthropomorphic robotic shells (androids and gynoids). They are typically used for menial labor jobs where pods are not as good of an option. Cheaper than many other morphs, they are commonly used for people who need a body quickly and cheaply or simply on a transient basis. Though they look humanoid, synths are easily recognizable as non-biological unless they have the synthetic mask option',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 SOM, +5 to one other aptitude of the player’s choice, Armor 6/6',
    disadvantages: 'Social Stigma (Clanking Masses) trait, Uncanny Valley trait',
    cp_cost: '30',
    credit_cost: 'High',
    mobility: 'Walker 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 24,
    name: 'Arachnoids',
    type: 'Synthetic Morph',
    description: 'Arachnoid robotic shells are 1-meter in length',
    details: 'Arachnoid robotic shells are 1-meter in length, segmented into two parts, with a smaller head like a spider or termite. They feature four pairs of 1.5-meter-long retractable arms/legs, capable of rotating around the axis of the body, with built-in pneumatic systems for propelling the bot with small leaps. The manipulator claws on each arm/leg can be switched out with extendable mini-wheels for high-speed skating movement. A smaller pair of manipulator arms near the head allows for closer handling and tool use. In zero-g environments, arachnoids can retract their arms/legs and maneuver with vectored air thrusters.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Enhanced Vision, Extra Limbs (10 Arms/Legs), Lidar, Mnemonic Augmentation, Pneumatic Limbs, Radar',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +10 SOM, Armor 8/8',
    disadvantages: '',
    cp_cost: '45',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Walker 4/24, Thrust Vector 8/40, Wheeled 8/40',
    speed: '1',
    variants:[],
  },
  {
    id: 25,
    name: 'Dragonfly',
    type: 'Synthetic Morph',
    description: 'The dragonfly robotic morph takes the shape of a meter-long',
    details: 'The dragonfly robotic morph takes the shape of a meter-long flexible shell with multiple wings and manipulator arms. Capable of near-silent turbofanaided flight in Earth gravity, dragonfly bots fare even better in microgravity.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation',
    aptitude_max: '30 (20 SOM)',
    durability: '25',
    wound_threshold: '5',
    advantages: 'Flight, +5 REF, Armor (2/2), dragonflies count as a small target (–10 to hit in combat)',
    disadvantages: '',
    cp_cost: '20',
    credit_cost: 'High',
    mobility: 'Winged 8/32',
    speed: '1',
    variants:[],
  },
  {
    id: 26,
    name: 'Flexbots',
    type: 'Synthetic Morph',
    description: 'Designed for multipurpose functions',
    details: 'Designed for multipurpose functions, flexbots can transform their shells to suit a range of situations and tasks. Their core frame consists of a half-dozen interlocking and shape-adjustable modules capable of auto-transforming into a variety of shapes: multi-legged walker, tentacle, hovercraft, and many others. Each module features its own sensor units and “bush robot” fractal-branching digits (capable of breaking into smaller digits, down to the micrometer scale, allowing for ultra-fine manipulation). The flexbot control computer is also distributed between modules. Individual flexbots are only the size of a large dog, but multiple flexbots can join together for larger mass operations, even taking on heavy-duty tasks such as demolition, excavation, manufacturing, robotics assembly, and so on.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Fractal Digits, Mnemonic Augmentation, Modular Design, Nanoscopic Vision, Shape Adjusting',
    aptitude_max: '30 (SOM 25)',
    durability: '25',
    wound_threshold: '5',
    advantages: 'Armor 4/4, individual flexbots count as a small target (–10 modifier to hit in combat)',
    disadvantages: '',
    cp_cost: '20',
    credit_cost: 'Expensive',
    mobility: 'Walker 4/16, Hover 8/40',
    speed: '1',
    variants:[],
  },
  {
    id: 27,
    name: 'Reaper',
    type: 'Synthetic Morph',
    description: 'The reaper is a common combat bot',
    details: 'The reaper is a common combat bot, used in place of biomorph soldiers and typically operated via teleoperation or by autonomous AI. The reaper’s core form is an armored disc, so that it can turn and present a thin profile to an enemy. It uses vector-thrust nozzles to maneuver in microgravity and also takes advantage of an ionic drive for fast movement over distance. Four legs/manipulating arms and four weapon pods are folded inside its frame. The reaper’s shell is made of smart materials, allowing these limbs and weapon mounts to extrude in any direction desired and even to change shape and length. In gravity environments, the reaper walks or hops on two or four of these limbs. Reapers are infamous due to numerous war XPs, and bringing one into most habitats will undoubtedly raise eyebrows if not get you arrested.',
    implants: '360-Degree Vision, Access Jacks, Anti-Glare, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Cyber Claws, Extra Limbs (4), Magnetic System, Mnemonic Augmentation, Pneumatic Limbs, Puppet Sock, Radar, Reflex Booster, Shape Adjusting, Structural Enhancement, T-Ray Emitter, Weapon Mount (Articulated, 4)',
    aptitude_max: '40',
    durability: '50 (60 with Structural Enhancement)',
    wound_threshold: '10 (12 w/Structural Enhancement)',
    advantages: '4 Limbs, +5 COO, +10 REF (+20 with Reflex Booster), +10 SOM, Armor 16/16',
    disadvantages: '',
    cp_cost: '100',
    credit_cost: 'Expensive (minimum 50,000+)',
    mobility: 'Walker 4/20, Hopper 4/20, Ionic 12/40, Vectored Thrust 4/20',
    speed: '2 (Reflex Booster)',
    variants:[],
  },
  {
    id: 28,
    name: 'Slitheroids',
    type: 'Synthetic Morph',
    description: 'Slitheroid bots are synthetic shells taking the form of a 2-meter-long segmented metallic snake',
    details: 'Slitheroid bots are synthetic shells taking the form of a 2-meter-long segmented metallic snake, with two retractable arms for tool use. Snake bots can coil, twist, and roll their bodies into a ball or hoop, moving either by slithering, burrowing, rolling, or pulling themselves along by their arms. The sensor suite and control computer are housed in the head.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Enhanced Vision, Mnemonic Augmentation',
    aptitude_max: '30',
    durability: '45',
    wound_threshold: '9',
    advantages: '+5 COO, +5 SOM, +5 to one other aptitude of the player’s choice, Armor 8/8',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Snake 4/16, Rolling 8/32',
    speed: '1',
    variants:[],
  },
  {
    id: 29,
    name: 'Swarmanoid',
    type: 'Synthetic Morph',
    description: 'The swarmanoid is not a single shell per se, but rather a swarm of hundreds of insect-sized robotic microdrones.',
    details: 'The swarmanoid is not a single shell per se, but rather a swarm of hundreds of insect-sized robotic microdrones. Each individual “bug” is capable of crawling, rolling, hopping several meters, or using nanocopter fan blades for airlift. The controlling computer, cortical stack, and sensor systems are distributed throughout the swarm. Though the swarm can “meld” together into a roughly child-sized shape, the swarm is incapable of tackling physical tasks like grabbing, lifting, or holding as a unit. Individual bugs are quite capable of interfacing with electronics.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmenta-tion, Swarm Composition',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: 'Damage and wounds are reflected as damaged/massacred bugs. The swarm may be “healed” by manufacturing more bugs.',
    disadvantages: 'Swarms cannot carry most gear or wear armor, and may not make strength-based SOM-linked skill tests.',
    cp_cost: '25',
    credit_cost: 'Expensive',
    mobility: 'Walker 2/8, Hopper 4/20, Rotor 4/32',
    speed: '1',
    variants:[],
  },
  {
    id: 30,
    name: 'Infomorph',
    type: 'Infomorph',
    description: 'Infomorphs are digital-only forms—they lack a physical body.',
    details: 'Infomorphs are digital-only forms—they lack a physical body. Infomorphs are sometimes carried by other characters instead of (or in addition to) a muse in a ghostrider module',
    implants: 'Mnemonic Augmentation',
    aptitude_max: '40',
    durability: '',
    wound_threshold: '',
    advantages: '',
    disadvantages: 'No physical form',
    cp_cost: '0',
    credit_cost: '0',
    mobility: 'None',
    speed: '3',
    variants:[],
  },
  {
    id: 31,
    name: 'Courier',
    type: 'Synthetic Morph',
    description: 'This synthmorph was specifically designed to fly between the many moons and habitats in the Saturnian system.',
    details: 'This synthmorph was specifically designed to fly between the many moons and habitats in the Saturnian system. It is used by both couriers and smugglers throughout the outer system. This morph appears to be a roughly humanoid head and torso set on a conical base, with a total height of 1.5 meters, that makes it look rather like a four-armed chess piece. This base contains both the morph’s ionic propulsion system, which doubles as a plasma sail in space, and an internal rocket. This miniature metallic hydrogen rocket is specifically designed for low thrust. It provides an acceleration of up to 0.25g, allowing the morph to take off and land on all moons and other small bodies in the solar system. This engine can operate for a total of one and a half hours before it requires refueling. The morph’s four slender arms fold flat against its torso when it is in flight. Its extensive sensor suit is useful for both navigation and various covert purposes.',
    implants: 'Access Jacks, Basic Mesh Inserts, Chemical Sniffer, Cortical Stack, Cryonic Protection, Cyberbrain, Direction Sense, Enhanced Vision, Extra Limbs (4), Grip Pads, Headlights, Hidden Compartment, Internal Rocket, Lidar, Magnetic System, Mnemonic Augmentation, Plasma Sail Implant, Radar, Retracting/Telescoping Limbs, T-ray Emitter.',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '4 Limbs, +5 COO, +5 INT, +5 REF, +5 to one other aptitude of the player’s choice, Armor 6/6',
    disadvantages: '',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Ionic 12/40, Thrust Vector 8/40',
    speed: '1',
    variants:[],
  },
  {
    id: 32,
    name: 'Fenrir',
    type: 'Synthetic Morph',
    description: 'Named for the monstrous wolf of Norse legend, the fenrir is one of the most imposing combat morphs ever developed.',
    details: 'Named for the monstrous wolf of Norse legend, the fenrir is one of the most imposing combat morphs ever developed. It is found only in the armed forces of the Hyoden city-state on Callisto (though black-market blueprints/copies are rumored to be available elsewhere). A massive, squat quadrupedal morph designed to be operated by up to six egos simultaneously, the fenrir is more akin to a super-heavy tank than a regular morph. It is possible that a single ego could fill all six ego slots at once through the use of alpha forks, but this has never been tested. The most common weapons mounted are linked HEAP and/or plasmaburst seeker launchers, exoatmospheric plasma beam bolters, and machine railguns loaded with AP rounds. Note: This morph is unique in that it allows more than one ego to use it at the same time. Ego Sharing may be purchased for this morph an additional four times, for a total of five additional egos.',
    implants: '360-Degree Vision, Access Jacks, Anti-Glare, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Direction Sense, Ego Sharing (1), Enhanced Hearing, Enhanced Vision, Extra Limbs (4), Heavy Combat Armor,Lidar, Mnemonic Augmentation, Pneumatic Limbs, Radar, Structural Enhancement, T-Ray Emitter, Weapon Mount (External, Articulated, 8)',
    aptitude_max: '35',
    durability: '70 (80 with Structural Enhancement)',
    wound_threshold: '14 (16 with Structural Enhancement)',
    advantages: '4 Limbs, +5 REF, +5 COO, +10 SOM, +5 to one other aptitude of the player’s choice, Armor 16/16 (32/32 with Heavy Combat Armor)',
    disadvantages: 'Large target (+10 to hit)',
    cp_cost: 'Not available at character creation',
    credit_cost: 'Expensive (rare and restricted; minimum 100,000+)',
    mobility: 'Walker 4/20, Thrust Vector 4/12',
    speed: '1',
    variants:[],
  },
  {
    id: 33,
    name: 'Hazer',
    type: 'Biomorph',
    description: 'Hazers are tall, fine-boned morphs, lightly muscled but heavily insulated against loss of body heat.',
    details: 'Hazers are tall, fine-boned morphs, lightly muscled but heavily insulated against loss of body heat. Even with all of their augmentations, hazers can’t survive exposure to the frigid atmosphere of Titan—but they can handle it slightly longer than other morphs. Hazers tend to be fair and slender, with chiseled features. Some have features so angular or elfin that their beauty is alien and unsettling to other human phenotypes. Striking Looks and Uncanny Valley are both common morph traits.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Enhanced Vision, Radiation Sense, Respirocytes, Temperature Tolerance (Improved Cold)',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COO, +5 WIL, +5 to two other aptitudes of the player’s choice',
    disadvantages: '',
    cp_cost: '35',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 34,
    name: 'Hulder',
    type: 'Biomorph',
    description: 'Hulder are engineered for survival in the Titanian wilds.',
    details: 'Hulder are engineered for survival in the Titanian wilds. In silhouette, their bodies resemble a long-legged great auk, though viewed up close, the resemblance to a bird ends. Hulder have no feathers, but rather smooth, rubbery charcoal or black skin covering a thick layer of nano-augmented blubber. What resembles a thick bill from a distance is actually a seamless protrusion of the face, packed with sensory augmentations. Hulder stand 2 meters tall and weigh on average 135 kilograms. Their sensory organs, webbed feet, and fingers are all cybernetic. Hulder can only tolerate temperatures hospitable to baseline transhumans for short periods of time. In the open, they must balance their bodies’ chemical reservoirs with other hulder and caribou once per month or with a chemical reserve pack. A typical band of 2–6 hulder and 10–20 caribou can go about a year before having to visit a hab or a station like Huvudskär to replenish chemical reserves.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Bioweave Armor (Light), Cortical Stack, Digging Claws, Direction Sense, Enhanced Vision, Long-Term Life Support, Oxygen Reserve, Radiation Sense, Swim Bladder, T-Ray Emitter, Temperature Tolerance (Cryonic)',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 SOM, +10 WIL, +5 to one aptitude of player’s choice',
    disadvantages: 'Temperature Intolerance (Warm)',
    cp_cost: '50',
    credit_cost: 'Expensive (Minimum 40,000+)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 35,
    name: 'Hyperbright',
    type: 'Biomorph',
    description: 'This morph is an attempt by a research team on Bright to create a successor to the menton',
    details: 'This morph is an attempt by a research team on Bright to create a successor to the menton, making it the most intelligence-enhanced morph ever created. Work on the hyperbright morph has been plagued with difficulties, as the designers attempt to push technical limits, creating a morph that can work at peak efficiency without distraction for long periods of time. In an effort to create a morph that proves their design and earns some positive reputation for their project, the creators took short cuts that caused the morph to have several distinctive and potentially annoying quirks, including an inherent need for drugs to stabilize its exotic neurochemistry. The result is a morph that is instantly recognizable by the brightly colored bony crest along the skull that helps cool its brain. Despite its quirks, the hyperbright has gained a small following among a number of scientists and engineers, especially since it has been optimized for use in the low-g environments of the outer system. When created or used on Bright, this morph is usually also fitted with the parallel processor nanoware',
    implants: 'Basic Biomods, Basic Mesh Inserts, Circadian Regulation, Cortical Stack, Eidetic Memory, Endocrine Control, Grip Pads, Hyper-Linguist, Math Boost, Mental Speed, Prehensile Feet',
    aptitude_max: '40 (COG and INT), 30 (all others)',
    durability: '35',
    wound_threshold: '7',
    advantages: '+15 COG, +10 INT, +5 WIL, +5 to one other aptitude of the player’s choice',
    disadvantages: 'Addiction (minor, to comfurt), Fast Metabolism, Uncanny Valley',
    cp_cost: '70',
    credit_cost: 'Expensive (Minimum 40,000+)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 36,
    name: 'Ring Flyer',
    type: 'Biomorph',
    description: 'Designed for use in Saturn’s magnetic field',
    details: 'Designed for use in Saturn’s magnetic field, this exotic biomorph is also occasionally used around Jupiter, Uranus, and Neptune, as well as having limited use in the Jovian Trojans and Main Belt. Easily recognizable with its slender limbs and round-backed torso, this morph can survive indefinitely in space, acquiring oxygen, water, and trace organic materials from the particles of Saturn’s rings. It can also maneuver around any planet with a magnetic field, flying swiftly and easily in any of these environments.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Bioweave Armor (Light), Cortical Stack, Enhanced Respiration, Enhanced Vision, Gas Jet System, Grip Pads, Hibernation, Long-Term Life Support, Medichines, Oxygen Reserve, Plasma Sail Implant, Prehensile Feet, Radiation Tolerance, Temperature Tolerance (Cryonic), Vacuum Sealing',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: 'Bioweave Armor (Light, 2/3), Limber (Level 1) trait, +5 COG, +5 COO, +5 REF, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '70',
    credit_cost: 'Expensive (Minimum 40,000+)',
    mobility: 'Winged 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 37,
    name: 'Savant',
    type: 'Synthetic Morph',
    description: 'This morph was developed on Ilmarinen as proof that synthmorphs can also be useful to scientists and engineers.',
    details: 'This morph was developed on Ilmarinen as proof that synthmorphs can also be useful to scientists and engineers. This strangely elegant morph lacks the disturbing mimicry of humanity found in synth and steel morphs. Instead, the ovoid head with its elegantly minimalist face looks more like an artistic sculpture than a metal version of a real human head.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Eidetic Memory, Hyper-Linguist, Math Boost, Mnemonic Augmentation',
    aptitude_max: '40 (COG and INT), 30 (all others)',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 COG, +5 INT, +5 SAV, +5 SOM, +5 to one other aptitude of the player’s choice, Armor 8/8',
    disadvantages: 'Social Stigma (Clanking Masses) trait',
    cp_cost: '65',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Walker 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 38,
    name: 'Selkie',
    type: 'Synthetic Morph',
    description: 'Selkies look like a human-seal hybrid',
    details: 'Selkies look like a human-seal hybrid, and in fact their genetics are aquanaut with heavy splices of seal traits. Their arms are standard human-shaped, but their legs are fused into a pair of hind flippers for powerful swimming. On land, they can stand but have difficulty moving, as they must flop, roll, or hop like a seal. They are adapted for the lack of air, deep cold, and crushing pressure of subcrustal seas.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Enhanced Vision, Enhanced Respiration, Gills, Hydrostatic Pressure Adaptation, Swim Bladder, Temperature Tolerance (Improved Cold), Toxin Filters',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +10 SOM, +5 to one other aptitude of the player’s choice, +10 Swimming skill',
    disadvantages: 'Movement Rate of 1/4 on land',
    cp_cost: '55',
    credit_cost: 'Expensive',
    mobility: 'Flippers 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 39,
    name: 'Aquanaut',
    type: 'Biomorph',
    description: 'Aquanauts are environmentally adapted for underwater activities.',
    details: 'Aquanauts are environmentally adapted for underwater activities. They have seen a revival on exoplanets with habitable seas and oceans. Their heart rate slows while underwater, their skin includes a layer of blubber that retains heat, they store oxygen in their muscle tissue, and they do not suffer negative health effects from pressure changes. Additionally, their eyes have nictitating membranes and their corneas adjust to counter underwater refraction. Their hands and feet are webbed and they possess a transgenic swim bladder for controlling buoyancy. They can safely descend to about 200 meters depth (roughly 21 atmospheres of pressure at 1 g) without suffering narcotic effects or other diving problems.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Enhanced Respiration, Gills, Sonar, Swim Bladder, Temperature Tolerance (Improved Cold), Toxin Filters',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +10 SOM, +5 to one other aptitude of the player’s choice, +10 Swimming skill',
    disadvantages: '',
    cp_cost: '50',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Aquanaut',
        details: 'equipped with hydrostatic pressure adaption for Cere'
      },
      {
        id: 2,
        name: 'Europan Aquanaut',
        details: 'equipped with hydrostatic pressure adaption for Europa'
      },
    ],
  },
  {
    id: 40,
    name: 'Crasher',
    type: 'Biomorph',
    description: 'An enhanced version of ruster morphs',
    details: 'An enhanced version of ruster morphs, crashers are rugged and durable designs capable of weathering a range of harsh environments. They are the ideal biomorph for gatecrashing assignments and are popular among first-in teams. Though pricey compared to other biomorph options, many gatecrashers traveling to less habitable and dangerous environments have found the investment worth it.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Bioweave Armor (Light), Circadian Regulation, Clean Metabolism, Cortical Stack, Direction Sense, Eidetic Memory, Enhanced Respiration, Enhanced Vision, Grip Pads, Hibernation, Medichines, Oxygen Reserve, Toxin Filters, Vacuum Sealing',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '9',
    advantages: 'Bioweave Armor (Light) (2/3), +5 COG, +10 SOM, +5 to three other aptitudes of the player’s choice',
    disadvantages: '',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 41,
    name: 'Digger',
    type: 'Pod',
    description: 'Diggers are worker pods customized for archeological work.',
    details: 'Diggers are worker pods customized for archeological work. They are used for surface surveys, excavation, and general physical labor by xenoarcheological teams. Their hands are modified digging claws, adapted from the genetics of hole-digging creatures like moles and aardvarks, though still flexible and useful for grasping and fine manipulation.',
    implants: 'Access Jacks, Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Digging Claws, Enhanced Vision, Mnemonic Augmentation, Puppet Sock, Wrist-Mounted Tools',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+10 SOM, +5 to one aptitude of the player’s choice',
    disadvantages: 'Social Stigma (Pod)',
    cp_cost: '30',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 42,
    name: 'Dvergr',
    type: 'Biomorph',
    description: 'Dvergar are biomorphs designed for comfortable operation in high-gravity environments.',
    details: 'Dvergar (plural of dvergr) are biomorphs designed for comfortable operation in high-gravity environments. They feature a reinforced skeletal structure and sturdier muscle masses. They are easily identified by their slightly squat, thick-necked, tough appearances.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, High-G Adaptation',
    aptitude_max: '35 (40 SOM)',
    durability: '45 (includes implant bonuses)',
    wound_threshold: '9',
    advantages: '+15 SOM (includes implant bonuses), +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '50',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 43,
    name: 'Kite',
    type: 'Synthetic Morph',
    description: 'This small shape-shifting synthetic shell is capable of flight no matter the atmospheric environment',
    details: 'This small shape-shifting synthetic shell is capable of flight no matter the atmospheric environment—or lack thereof. Its default mode is turbofan-driven rotorcraft; its light weight allows it to fly and hover even in thin atmospheres and heavy gravities. In streamlined ionic mode, it can travel at high speeds and maneuver in hurricane-force winds. In vacuum, it can drive itself with thrust-vector nozzles. Sometimes called “multifliers,” kites are popular among gatecrashers and gatehoppers due to their adaptability and usefulness for aerial recon and surveys.',
    implants: 'Access Jacks, Anti-Glare, Basic Mesh Inserts, Chemical Sniffer, Cortical Stack, Cyberbrain, Direction Sense, Enhanced Hearing, Enhanced Vision, Lidar, Mnemonic Augmentation, Radar, Shape Adjusting, T-Ray Emitter',
    aptitude_max: '25',
    durability: '20',
    wound_threshold: '4',
    advantages: 'Flight, +5 to one aptitude of the player’s choice, Armor (2/2), counts as a small target in combat (–10 to hit)',
    disadvantages: '',
    cp_cost: '30',
    credit_cost: 'High',
    mobility: 'Ionic 12/40, Thrust Vector 8/40, Walker 2/8, Winged 8/32',
    speed: '1',
    variants:[],
  },
  {
    id: 44,
    name: 'Ripwing',
    type: 'Pod',
    description: 'Ripwings are neogenetic avians',
    details: 'Developed by the genehackers of Fortean, ripwings are neogenetic avians, incorporating genetics from a range of flying creatures, some of them prehistoric pterosaur genes acquired from Sky Ark researchers, along with some original genetic traits. These transgenic amalgamations are larger and sturdier than standard neo-avian morphs. They are popular among both neo-avian mercurials who want a more robust form and gatecrashers looking for a quick and stealthy flyer for recon missions. The ripwing morph makes more extensive use of the chiroptera genestocks used to give the first avian uplifts functional hands. Instead of feathers, ripwings feature tough leathery skin or even scales. The morphs are usually a uniform matte black in color, though they are able to change color at will due to their chameleon skin enhancements.',
    implants: 'Access Jacks, Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Cyberbrain, Enhanced Vision, Mnemonic Augmentation, Prehensile Feet, Puppet Sock, Wings',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Beak/Claw Attack (1d10 DV, use Unarmed Combat skill), Flight, +5 COO, +5 INT, +5 REF',
    disadvantages: 'Social Stigma (Neogenetic), Social Stigma (Pod)',
    cp_cost: '40',
    credit_cost: 'Expensive (minimum 30,000)',
    mobility: 'Feet 4/20, Winged 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 45,
    name: 'Scurrier',
    type: 'Pod',
    description: 'Scurriers are pods developed from the non-sapient extraterrestrials known as sciurids',
    details: 'Scurriers are pods developed from the non-sapient extraterrestrials known as sciurids. In appearance, scurrier pods are similar to raccoon-sized flying squirrels with a lash-like manipulator rather than a fluffy tail, though still regarded as highly cute. They make excellent climbers and are capable of gliding due to the membrane between their limbs. Scurriers are gaining popularity for their usefulness in exploring tunnels and small areas as well as high areas reached by climbing. They have also been used for maintenance and tech works tasks due to their nimbleness and manual dexterity.',
    implants: 'Access Jacks, Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Gliding Membrane, Mnemonic Augmentation, Prehensile Tail, Puppet Sock',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 SAV, +10 COO, 6 Limbs, Limber (Level 1) Trait, +10 Climbing skill, +10 Freerunning skill, counts as a small target in combat (–10 to hit)',
    disadvantages: 'Alien Biochemistry, Social Stigma (Alien), Social Stigma (Pod)',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 46,
    name: 'Spare',
    type: 'Synthetic Morph',
    description: 'Spare morphs are small, cheap, lightweight, synthetic shells designed to be used as a replacement',
    details: 'Spare morphs are small, cheap, lightweight, synthetic shells designed to be used as a replacement should someone’s original morph be killed or destroyed. A cortical stack (retrieved from the character’s previous morph) can be easily plugged into the spare morph, effectively resleeving them (they must make Integration, Alienation, and Continuity Tests as normal). Once plugged in, it takes only 3 Action Turns for the cortical stack’s data to be read and checked for integrity and the ego to run inside the spare’s cyberbrain. Spares are designed for portability. Packed as a flat disc 15 centimeters in diameter and with a mass of 2 kilograms, when activated they pop into a spherical shape with 6 slender and retractable 20-centimeter limbs (3 arms and 3 legs). They are a common piece of equipment for gatecrashing teams.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cyberbrain, Extra Limbs (3 Arms/3 Legs), Grip Pads, Mnemonic Augmentation, Puppet Sock',
    aptitude_max: '20',
    durability: '15',
    wound_threshold: '3',
    advantages: 'Armor (2/2), counts as a small target in combat (–10 to hit)',
    disadvantages: 'Social Stigma (Clanking Masses)',
    cp_cost: '5',
    credit_cost: 'Moderate',
    mobility: 'Walker (2/8)',
    speed: '1',
    variants:[],
  },
  {
    id: 47,
    name: 'Whiplash',
    type: 'Pod',
    description: 'Whiplash pods are bioengineered from planimal stock found on Sunrise',
    details: 'Designed by autonomist xenobotanists as an experiment in developing a cyberbrain/planimal interface, whiplash pods are bioengineered from planimal stock found on Sunrise, with other transgenic features. Whiplash pods are gaining some traction among gatecrashers due to their ability to blend in to arboreal environments. The primary modification made to the whiplash stock was to turn the entire organism upside down and orient the digestive portion of the organism horizontally, so that the whiplash’s trilobed orifice faces forward. The whiplash’s grasping roots were also converted into even more motile “walking tentacles” borrowed from other Sunrise planimals. Other adjustments include the addition of a pair of grasping limbs, each with four universally opposable digits; artificial sensing mods (providing transhuman-standard sensing ability); and a general toughening of the internal structure for rigidity and support. The barrel-like body remains very similar to the original planimal stock and, reorientation notwithstanding, the digestive system remains mostly unchanged. The ability to extend and retract the whiplash’s feeding tendril was heavily enhanced, so now the tendril acts more like a two-meter-long chameleon-like tongue than a hanging food-trap.',
    implants: 'Access Jacks, Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Puppet Sock',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: 'Tendril Attack (use Unarmed Combat skill, 1d10 + (SOM ÷ 10) DV, +10 to disarming called shot attacks), +5 COO, +10 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: 'Alien Biochemistry, Social Stigma (Alien), Social Stigma (Pod)',
    cp_cost: '50',
    credit_cost: 'Expensive (rare; minimum 50,000+)',
    mobility: 'Tenticles 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 48,
    name: 'Xu Fu',
    type: 'Synthetic Morph',
    description: 'Many gatecrashers consider xu fus the ideal exoplanet exploration synthmorph',
    details: 'Named after a historical Chinese explorer, many gatecrashers consider xu fus the ideal exoplanet exploration synthmorph. Its main body sits atop 6 legs (up to 2 meters long, though retractable) that end in multidirectional smart wheels for quick travel, capable of rolling in any direction and over rough terrain. For exceptionally difficult terrain, the wheels can be retracted and the xu fu can maneuver as a walker. In addition to two standard arms, it features a third 2-meter long sensor-equipped limb for reaching far distances, overseeing obstacles, etc. Xu fus have an impressive sensor package and are ideal for surface-based scouting as well as investigating tunnels, collecting samples, and so on.',
    implants: '360° Vision, Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Direction Sense, Echolocation, Electrical Sense, Enhanced Hearing, Enhanced Vision, Extra Limbs (3 Arms/6 Legs), Grip Pads, Lidar, Mnemonic Augmentation, Pneumatic Limbs, Radar, Puppet Sock, Radiation Sense, Telescoping Limbs (Legs, 1 Arm), T-Ray Emitter',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, + 5 SOM, Armor (8/8)',
    disadvantages: '',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 50,000+)',
    mobility: 'Walker 4/20, Wheeled 4/32',
    speed: '1',
    variants:[],
  },
  {
    id: 49,
    name: 'Lunar Flyer',
    type: 'Biomorph',
    description: 'This morph is a version of the exalt morph that has been adapted to fly in Earth normal air pressure',
    details: 'This morph is a version of the exalt morph that has been adapted to fly in Earth normal air pressure as long as the gravity is 0.2 g or less. Though this morph is available on other low-g worlds and habitats, it was developed for and is primarily found on Luna. This morph resembles a typical exalt morph, except that it is lightly built, has larger lungs, and has feathered wings with a wingspan of 3 meters. The wings come out of the back torso and leave the morph’s hands and wrists unhindered. The wings may also be folded behind the body.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Enhanced Vision, Wings',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: 'Flight, +5 COG, +5 COO, +5 to two other aptitudes—player’s choice',
    disadvantages: '',
    cp_cost: '35',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20, Winged 8/40',
    speed: '1',
    variants:[
      {
        id: 1,
        name: 'Titanian Fliers',
        details: 'Lunar fliers augmented with temperature tolerance (improved cold). CP and Credit Costs remain the same.'
      },
    ],
  },
  {
    id: 50,
    name: 'Martian Alpiner',
    type: 'Biomorph',
    description: 'Alpiners were a relatively common biomorph design on early frontier Mars',
    details: 'Alpiners were a relatively common biomorph design on early frontier Mars, when temperatures and atmospheric pressure had not yet risen to present levels. Now they are found predominantly in the city of Olympus, where environmental conditions will always be incredibly harsh. Avid rock climbers and outdoor types also favor this morph, and in recent years it has enjoyed an unusual vogue among chic urbanites going for a rough-and-ready look without sleeving in the more de classe ruster morph.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Direction Sense, Grip Pads, Low Pressure Tolerance, Oxygen Reserve, Respirocytes, Temperature Tolerance (Improved Cold)',
    aptitude_max: '25',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 SOM, +10 Climbing skill',
    disadvantages: 'Fast Metabolism trait, Planned Obsolescence trait',
    cp_cost: '30',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 51,
    name: 'Neanderthal',
    type: 'Biomorph',
    description: 'This morph is based on fossilized Neanderthal DNA',
    details: 'This morph is based on fossilized Neanderthal DNA, uplifted and enhanced to transhuman equivalence. Neanderthal morphs look like muscular humans with a heavy bone structure, distinctively long skulls, heavy brow ridges, and weak chins. Pale complexions and red hair are common features.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COG, +5 INT, +10 SOM, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 52,
    name: 'Q-Morph',
    type: 'Synthetic Morph',
    description: 'Quartz morphs are the primary shell design used for Venusian surface mining',
    details: 'Quartz morphs, commonly called Q-morphs, are the primary shell design used for Venusian surface mining. Constructed from quartz and extremely durable alloys, Q-morphs look like four-legged crabs with two pairs of arms. The lower pair of arms is designed for strength, the upper pair for precision and dexterity. This morph is squat, exceptionally tough, and completely unable to function in temperatures below 250 C.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Direction Sense, Echolocation, Enhanced Vision, Extreme Heat Shielding, Extreme Pressure Adaptation, Mnemonic Augmentation, Radar, T-Ray Emitter, Wrist-Mounted Tools',
    aptitude_max: '30',
    durability: '120',
    wound_threshold: '24',
    advantages: 'High Temperature Operation trait, 8 limbs, Claw Attack (DV 2d10), –5 COO, +10 SOM, +5 to one other aptitude of the player’s choice, Armor 18/18',
    disadvantages: 'Only works on the Venusian surface or in similar hot and high pressure environments',
    cp_cost: '100',
    credit_cost: 'Expensive (minimum 60,000+)',
    mobility: 'Walker 2/4',
    speed: '1',
    variants:[],
  },
  {
    id: 53,
    name: 'Salamander',
    type: 'Biomorph',
    description: 'Salamanders are a type of biomorph popular with Solarians.',
    details: 'Salamanders are a type of biomorph popular with Solarians. They share some of the physiological traits of suryas, but are unable to survive unprotected in the corona (requiring a solar survival suit, like other biomorphs), and are instead bio-engineered to survive in the protected vacuum of coronal habitats. Their skin is thick, hairless, vaguely reptilian, and mostly black in color, with gold and orange body patterning. Like suryas, salamanders communicate either via wireless transmissions or by “sunspotting”—using their chromatophores to shift light and dark patterns on their skin to form patterns easily comprehensible to other coronal morphs. Salamanders have a wiry, streamlined, swept-back sort of look, a combination of fey and monkey-like. Their heads are also somewhat reptilian, with reflective eyes, no nose, and no mouth. Their feet are prehensile, usable just like hands. They lack reproductive organs and capabilities and feature cyberware gas jets on their chest and back for maneuvering in zero g. Many Solarians who normally inhabit suryas will sleeve into salamanders if they need to use humanoid tools or interact with non-Solarians.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Chameleon Skin, Enhanced Vision, Gas Jet System, Medichines, Oxygen Reserve, Prehensile Feet, Vacuum Sealing',
    aptitude_max: '30',
    durability: '60',
    wound_threshold: '12',
    advantages: 'Coronal Adaptation (solar metabolism only) trait, Limber (Level 1) trait, +5 COO, +5 INT, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants:[],
  },
  {
    id: 54,
    name: 'Steel Morph',
    type: 'Synthetic Morph',
    description: 'This morph was developed by technicians and designers who are members of the Lunar synthmorph rights movement',
    details: 'This morph was developed by technicians and designers who are members of the Lunar synthmorph rights movement, the Steel Liberators. Middle-class Lunars who came out of poverty and continue to actively support the Steel Liberators sometimes choose this morph, despite the fact that this choice often results in them experiencing significant prejudice from biochauvinists.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Eidetic Memory, Mnemonic Augmentation',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 SOM, +5 COG, +5 to two other aptitudes of the player’s choice, Armor 8/8',
    disadvantages: 'Social Stigma (Clanking Masses) trait, Uncanny Valley trait',
    cp_cost: '50',
    credit_cost: 'Expensive (minimum 30,000+)',
    mobility: 'Walker (4/20)',
    speed: '1',
    variants:[],
  },
  {
    id: 55,
    name: 'Steel Morph (Masked Variant)',
    type: 'Synthetic Morph',
    description: 'This version of the steel morph is equipped with the synthetic mask enhancement',
    details: 'This version of the steel morph is equipped with the synthetic mask enhancement, making the shell look like a human biomorph. This version is uncommon, as most Steel Liberators view biological masking as a form of “selling out.” It is used both by Lunars who are stuck sleeving into a synthmorph, but whom don’t want to suffer discrimination, and by Steel Liberator activists looking to infiltrate biochauvinists and other opponent groups.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Eidetic Memory, Mnemonic Augmentation',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 SOM, +5 COG, +5 to two other aptitudes of the player’s choice, Armor 8/8, Synthetic Mask',
    disadvantages: '',
    cp_cost: '55',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Walker (4/20)',
    speed: '1',
    variants:[],
  },
  {
    id: 56,
    name: 'Steel Morph (Luquid Silver Variant)',
    type: 'Synthetic Morph',
    description: 'Designed as a top-end version of the steel morph',
    details: 'Designed as a top-end version of the steel morph, this shell\'s entire outer covering is composed of active nanomachines. A number of synthmorph performers use this shell\'s shape- and color-altering capacities as part of their acts. However, the fact that this morph can disguise itself as any other humanoid synthmorph, including the ubiquitous case morph, means that a number of covert operatives and criminals also make use of this morph. This version of the steel morph cannot use a synthetic mask.',
    implants: 'Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Eidetic Memory, Mnemonic Augmentation, Shape Adjusting, Skinflex, Wrist-Mounted Tools',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 SOM, +5 COG, +5 to three other aptitudes of the player’s choice, Armor 8/8',
    disadvantages: 'Social Stigma (Clanking Masses) trait, Uncanny Valley trait',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Walker (4/20)',
    speed: '1',
  },
  {
    id: 57,
    name: 'Sundiver',
    type: 'Synthetic Morph',
    description: 'The sundiver is a synthetic morph designed for solar research and emergency rescue operations',
    details: 'The sundiver is a synthetic morph designed for solar research and emergency rescue operations. Sundivers are sleek mechanisms, about six meters long. They look a little like ramjets, except for a pair of articulated arms that extend forward from the morph’s pointed nose, allowing it to reach for and grasp objects. Because sundivers operate in the coronal environment, they are built to survive superheated plasma and shielded against radiation. Sundivers are equipped with a powerful electromagnetic propulsion system that allows them to skate along solar magnetic lines of force much like the surya do.',
    implants: '360-Degree Vision, Access Jacks, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Enhanced Vision, Heavy Combat Armor, Mnemonic Augmentation, Radar, Reflex Booster',
    aptitude_max: '30',
    durability: '120',
    wound_threshold: '24',
    advantages: 'Coronal Adaptation, +5 COO, +10 REF (+20 with Reflex Booster), Armor 16/16',
    disadvantages: 'Large Target combat modifier',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Thrust Vector 12/60',
    speed: '2 (Reflex Booster)',
  },
  {
    id: 58,
    name: 'Surya',
    type: 'Biomorph',
    description: 'Suryas swim freely in the sun’s corona',
    details: 'Named for a Hindu sun deity, suryas swim freely in the sun’s corona. Looking roughly like whales or orcas, suryas may reach lengths of ten meters or more. They generate powerful magnetic fields that shield them from solar radiation and heat, while allowing them to surf the solar wind and extract ionized particles. Strong bones and connective tissues protect against the crushing solar gravity. Beneath their thick hides are channels of liquid water interleaved with layers of fat which serve to shield the organism from harmful radiation. Engineered medichines repair tissue damaged by radiation and convert hydrogen ions into water. A surya’s skin is an extraordinary organ, embedded with chromatophores that allow them to transmit alternating patterns of light and dark for communication. In addition, a lateral line runs down their sides, allowing them to detect the long-period sound waves that reflect off the sun’s lower atmosphere and resonate through the corona’s gas and plasma. Suryas traveling through the transition zone between the corona and the chromosphere use these vibrations to predict and avoid heavy solar weather.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Enhanced Hearing, Enhanced Vision, Lateral Line, Medichines, Vacuum Sealing',
    aptitude_max: '30',
    durability: '100',
    wound_threshold: '20',
    advantages: 'Coronal Adaptation trait, +10 COO, +5 REF, +5 SOM, +10 Free Fall skill',
    disadvantages: 'Large Target combat modifier',
    cp_cost: '50',
    credit_cost: 'Expensive (minimum 30,000+)',
    mobility: 'Thrust Vector 8/40',
    speed: '1',
  },
  {
    id: 59,
    name: 'Venusian Glider',
    type: 'Biomorph',
    description: 'The glider is designed to survive for many hours in Venus’s unbreathable atmosphere',
    details: 'The glider is designed to survive for many hours in Venus’s unbreathable atmosphere. Tall and thin, with long, strong limbs and a lightweight build, this morph also features gliding membranes (p. 166) that allow it to soar through the upper Venusian atmosphere. It can even gain altitude by riding thermals (which it can see using its enhanced vision). Once Venusian terraforming efforts are complete, an upgraded version of this morph will be able to breathe normally.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Enhanced Respiration, Enhanced Vision, Gliding Membranes, Grip Pads, Prehensile Feet, Respirocytes',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: 'Limber (Level 1) trait, +5 REF, +5 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Winged 4/20',
    speed: '1',
  },
  {
    id: 60,
    name: 'Chickcharnie',
    type: 'Pod',
    description: 'This morph is a modified version of a resurrected species',
    details: 'Another creation by the mad geniuses of the exoplanet Fortean, this morph is a modified version of a resurrected species. The extinct Tyto Pollens was a large pre-Columbian flightless ground owl species in the Caribbean. The chickcharnie was rumored to be a supernatural variant of this bird that haunted the forests bestowing boons or curses upon travelers depending on how they treated it. The Fortean version of the chickcharnie is best described as a humanoid owl. Over one meter in height, it is bipedal but stands shorter than humans. Though winged, it is flightless except in very low grav environments and microgravity. Its wing design, however, incorporates a functional set of clawed hands. The chickcharnie is growing in popularity among neo-avians who don’t mind sacrificing flight for physical resilience, more functional hands, and a stature closely approximating transhuman standards.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Prehensile Feet, Puppet Sock',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Beak/Claw Attack (1d10 DV, use Unarmed Combat skill), +5 COO, +5 INT, +10 REF',
    disadvantages: '',
    cp_cost: '35',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 61,
    name: 'Gargoyle',
    type: 'Synthetic Morph',
    description: 'Gargoyles are an anthroform synthetic morph designed as a mobile sensor unit',
    details: 'Gargoyles are an anthroform synthetic morph designed as a mobile sensor unit. They are used by media, freelance journalists, forensics teams, and anyone who is regularly required to document a situation thoroughly. Though humanoid in shape, gargoyles stand taller than average transhumans for better viewing. Much of their exterior surface is covered in quantum dot camera-displays.',
    implants: '360-Degree Vision, Access Jacks, Anti-Glare, Basic Mesh Inserts, Chemical Sniffer, Cortical Stack, Cyberbrain, Enhanced Hearing, Enhanced Smell, Enhanced Vision, Lidar, Mnemonic Augmentation, Nanoscopic Vision, Oracles, Radar, T-Ray Emitter',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 INT, +5 to one aptitude of the player’s choice, Armor 6/6',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
    mobility: 'Walker 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 62,
    name: 'Hypergibbon',
    type: 'Pod',
    description: 'Built from siamang genestock, the largest of the lesser apes',
    details: 'Built from siamang genestock, the largest of the lesser apes, hypergibbons are often mistaken for uplifts, although this is not the case. The gibbon was never a candidate for uplift due to a brain anatomy considerably more primitive than great apes. With the addition of a cyberbrain, though, they make excellent pods. Many primate uplifts choose hypergibbons in place of other pods or when they need something small like a neotenic. Hypergibbons stand about 1 meter tall, weigh 15 kilograms, and typically have black fur and skin (although bodysculpting permits many variations). They have inflatable throat sacks that allow melodious calls that carry great distances. Their wrists feature a ball-and-socket joint and also naturally dislocate to enable easier swinging by the arms.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Prehensile Feet, Puppet Sock',
    aptitude_max: '30',
    durability: '25',
    wound_threshold: '5',
    advantages: '+5 INT, +5 REF, +10 Climbing skill, +20 Freerunning skill, Limber (Level 2) trait, hypergibbons count as a small target in combat (–10 to hit)',
    disadvantages: 'Social Stigma (Pod)',
    cp_cost: '30',
    credit_cost: 'Expensive',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 63,
    name: 'Neo-Beluga',
    type: 'Biomorph',
    description: 'Neo-belugas are the smallest and most numerous of the surviving whale uplifts',
    details: 'Neo-belugas are the smallest and most numerous of the surviving whale uplifts, ranging 5.5 meters in length on average. They are white-skinned with no dorsal ridge, toothed, and have the distinction of being the only whale that can swim backwards.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Oxygen Reserve',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COO, +5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +40 Swimming skill, Ramming Attack (1d10 DV)',
    disadvantages: 'Neo-belugas lack a sense of smell and count as a large target in combat (+10 to hit)',
    cp_cost: '45',
    credit_cost: 'Expensive (minimum 40,000+)',
    mobility: 'Swim 16/40',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Neo-Cetaceans',
        details: 'Neo-cetaceans modified for survival on Ceres also have gills, hydrostatic pressure adaption, temperature tolerance (improved cold), and toxin filters. Increase CP Cost by 10; Credit Cost remains the same.'
      },
      {
        id: 2,
        name: 'Europan Uplifts',
        details: 'Neo-cetaceans and neo-octopi are natural fits for the Europan environment. Any of these morphs (including the takko) can be modified for survival on Europa, adding hydrostatic pressure adaption and temperature tolerance (improved cold). Increase CP Cost by 5; Credit Cost remains the same.'
      },
    ],
  },
  {
    id: 64,
    name: 'Neo-Dolphin',
    type: 'Biomorph',
    description: 'The uplifted versions of various dolphin species',
    details: 'The uplifted versions of various dolphin species are very similar to baseline dolphins physiologically. Thanks to the oxygen reserve implant, neo-dolphins can stay underwater for longer (Cerean dolphins have gills installed, as the subcrustal sea has no breathable atmosphere above it). Common neo-dolphin germlines lack hands or other limbs, though cybernetic arms or even bioware enhancements are not uncommon. Neo-dolphin morphs are very rare, since there are few habitats that can support them, and they are almost never found apart from aquatic environments.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Oxygen Reserve',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 COO, +5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +40 Swimming skill, Ramming Attack (1d10 DV, use Unarmed Combat skill)',
    disadvantages: 'Neo-dolphins lack a sense of smell.',
    cp_cost: '40',
    credit_cost: 'Expensive (minimum 35,000)',
    mobility: 'Swim 16/48',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Neo-Cetaceans',
        details: 'Neo-cetaceans modified for survival on Ceres also have gills, hydrostatic pressure adaption, temperature tolerance (improved cold), and toxin filters. Increase CP Cost by 10; Credit Cost remains the same.'
      },
      {
        id: 2,
        name: 'Europan Uplifts',
        details: 'Neo-cetaceans and neo-octopi are natural fits for the Europan environment. Any of these morphs (including the takko) can be modified for survival on Europa, adding hydrostatic pressure adaption and temperature tolerance (improved cold). Increase CP Cost by 5; Credit Cost remains the same.'
      },
    ],
  },
  {
    id: 65,
    name: 'Neo-Hominid (Gorillas)',
    type: 'Biomorph',
    description: '',
    details: 'To highlight the differences in neo-hominid species, apply the following stats for neo-gorillas. The neo-hominid entry in the Eclipse Phase core rulebook applies for neo-chimpanzees, neo-bonobos, and neo-orangutans.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Prehensile Feet',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 INT, +10 SOM, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '35',
    credit_cost: 'Expensive (minimum 30,000)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 66,
    name: 'Neo-Orca',
    type: 'Biomorph',
    description: 'Uplifted Orcas',
    details: 'Though colloquially referred to as killer whales, orcas are actually members of the dolphin family. The average neo-orca length is 7 meters for males, 6 meters for females. Males also have larger and more triangular pectoral fins.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Oxygen Reserve',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +5 INT, +10 SOM, +5 to one other aptitude of the player’s choice, +40 Swimming skill, +20 Unarmed Combat skill, Bite Attack (2d10 DV, use Unarmed Combat skill)',
    disadvantages: 'Neo-orcas lack a sense of smell and count as a large target in combat (+10 to hit)',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 50,000)',
    mobility: 'Swim 16/60',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Neo-Cetaceans',
        details: 'Neo-cetaceans modified for survival on Ceres also have gills, hydrostatic pressure adaption, temperature tolerance (improved cold), and toxin filters. Increase CP Cost by 10; Credit Cost remains the same.'
      },
      {
        id: 2,
        name: 'Europan Orca',
        details: 'The greatest success to date is the Europan orca, a cetacean uplift that upgrades the neo-orca with carapace armor, eelware, enhanced vision, hydrostatic pressure adaption and temperature tolerance (improved cold). Increase CP Cost by 10; Credit Cost remains the same. These are especially useful as undersea guards or mercenaries.'
      },
    ],
  },
  {
    id: 67,
    name: 'Neo-Pig',
    type: 'Biomorph',
    description: 'Uplifted pig morphs are bipedal',
    details: 'Uplifted pig morphs are bipedal and feature transgenic hands, feet, and vocal systems. They tend to be slightly shorter than the average transhuman but much stockier. Males grow tusks from their lower jaws',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 SOM, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '20',
    credit_cost: 'High',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 68,
    name: 'Neo-Porpoise',
    type: 'Biomorph',
    description: 'Neo-porpoises are smaller but very similar to neo-dolphins',
    details: 'Neo-porpoises are smaller but very similar to neo-dolphins and similarly are much like their baseline relatives. They average 2.5 meters in length.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Oxygen Reserve',
    aptitude_max: '25',
    durability: '25',
    wound_threshold: '5',
    advantages: '+5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +50 Swimming skill, Ramming Attack (1d10 DV)',
    disadvantages: 'Neo-porpoises lack a sense of smell.',
    cp_cost: '35',
    credit_cost: 'Expensive (minimum 30,000)',
    mobility: 'Swim 16/56',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Neo-Cetaceans',
        details: 'Neo-cetaceans modified for survival on Ceres also have gills, hydrostatic pressure adaption, temperature tolerance (improved cold), and toxin filters. Increase CP Cost by 10; Credit Cost remains the same.'
      },
      {
        id: 2,
        name: 'Europan Uplifts',
        details: 'Neo-cetaceans and neo-octopi are natural fits for the Europan environment. Any of these morphs (including the takko) can be modified for survival on Europa, adding hydrostatic pressure adaption and temperature tolerance (improved cold). Increase CP Cost by 5; Credit Cost remains the same.'
      },
    ],
  },
  {
    id: 69,
    name: 'Neo-Whale',
    type: 'Biomorph',
    description: 'Less than several hundred neo-whale morphs exist',
    details: 'Less than several hundred neo-whale morphs exist, and the majority remain occupied by their original egos. They are primarily found in Ceres and Atlantica. They are derived from humpback, blue, and sperm whale genetic stock. Humpbacks and blues are baleen whales and require large amounts of krill to survive. Sperm whales are toothed, feeding on fish and squid.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Echolocation, Enhanced Hearing, Oxygen Reserve',
    aptitude_max: '30',
    durability: '100',
    wound_threshold: '20',
    advantages: '+5 COO, +5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +40 Swimming skill, Ramming Attack (2d10 DV, use Unarmed Combat skill), Bite Attack (4d10 DV, sperm whales only, use Unarmed Combat skill)',
    disadvantages: 'Neo-whales lack a sense of smell and count as a very large target in combat (+30 to hit)',
    cp_cost: '75',
    credit_cost: 'Expensive (exceptionally rare; minimum 75,000)',
    mobility: 'Swim 16/40',
    speed: '1',
    variants: [
      {
        id: 1,
        name: 'Cerean Neo-Cetaceans',
        details: 'Neo-cetaceans modified for survival on Ceres also have gills, hydrostatic pressure adaption, temperature tolerance (improved cold), and toxin filters. Increase CP Cost by 10; Credit Cost remains the same.'
      },
      {
        id: 2,
        name: 'Europan Uplifts',
        details: 'Neo-cetaceans and neo-octopi are natural fits for the Europan environment. Any of these morphs (including the takko) can be modified for survival on Europa, adding hydrostatic pressure adaption and temperature tolerance (improved cold). Increase CP Cost by 5; Credit Cost remains the same.'
      },
    ],
  },
  {
    id: 70,
    name: 'Shapers',
    type: 'Pod',
    description: 'Shapers are the ultimate disguise morph',
    details: 'Shapers are the ultimate disguise morph. Constructed as pods, the default shaper look is intentionally generic, based on the computer-generated composite average look of the solar system’s residents. They lack the distinctive seam lines applied to most pod morph designs. The skinflex system allows the morph to quickly change its outward appearance. Additional modifications help the morph evade or fool sensor and biometric systems. Shapers are a favorite tool for spies and are excellent for infiltration or fooling surveillance. They are often remotely operated via puppet sock. Shapers are illegal in many habitats.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Clean Metabolism, Cortical Stack, Cyberbrain, Emotional Dampers, Gait Masking, Mnemonic Augmentation, Nanotat ID Flux, Puppet Sock, Sex Switch, Skinflex',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 INT, +5 SAV, +5 to one aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '45',
    credit_cost: 'Expensive (minimum 40,000)',
    mobility: 'Feet 4/20',
    speed: '1',
    variants: [],
  },
  {
    id: 71,
    name: 'Skulker',
    type: 'Synthetic Morph',
    description: 'Skulkers are a stealth swarmanoid designed to infiltrate sensitive areas and avoid detection by sensors.',
    details: 'Skulkers are a stealth swarmanoid designed to infiltrate sensitive areas and avoid detection by sensors.',
    implants: 'Access Jacks, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Radar Invisibility, Swarm Composition',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: 'Damage and wounds are reflected as damaged/massacred bugs. The swarm may be “healed” by manufacturing more bugs.',
    disadvantages: 'Swarms cannot carry most gear or wear armor, and may not make strength-based SOM-linked skill tests.',
    cp_cost: '35',
    credit_cost: 'Expensive (minimum 30,000)',
    mobility: 'Walker 2/8, Hopper 4/20, Rotor 4/32',
    speed: '1',
    variants: [],
  },
  {
    id: 72,
    name: 'Takko',
    type: 'Synthetic Morph',
    description: 'The first synthetic octopus design from the engineers at Feral Robot',
    details: 'The first synthetic octopus design from the engineers at Feral Robot is a hardy shell custom-designed to make octopi uplifts feel more at home in a synthetic body with eight functioning appendages. Though it lacks ink sacs, the takko features vectored-thrust jets for microgravity propulsion.',
    implants: '360-Degree Vision, Access Jacks, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Cyberbrain, Enhanced Vision, Extra Limbs (8 Arms), Grip Pads, Mnemonic Augmentation, Polarization Vision',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: 'Beak Attack (1d10 + 2 DV, use Unarmed Combat skill), +10 Free Fall skill, +10 Climbing skill,+5 COO, +5 INT, +5 SOM, Armor 8/8',
    disadvantages: '',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 45,000+)',
    mobility: 'Walker 4/24, Thrust Vector 8/40',
    speed: '1',
    variants: [],
  },
]

export default function Morphs() {
  const [selectedMorph, setSelectedMorph] = useState(null)

  const renderDetails = (item) => (
    <>
      <h3>{item.name}</h3>
      <p>{item.details}</p>
      <p><strong>Type:</strong> {item.type}</p>
      <p><strong>Implants:</strong> {item.implants}</p>
      <p><strong>Mobility System:</strong> {item.mobility}</p>
      <p><strong>Aptitude Maximum:</strong> {item.aptitude_max}</p>
      <p><strong>Speed:</strong> {item.speed}</p>
      <p><strong>Durability:</strong> {item.durability}</p>
      <p><strong>Wound Threshold:</strong> {item.wound_threshold}</p>
      <p><strong>Advantages:</strong> {item.advantages}</p>
      <p><strong>Disadvantages:</strong> {item.disadvantages}</p>
      <p><strong>CP Cost:</strong> {item.cp_cost}</p>
      <p><strong>Credit Cost:</strong> {item.credit_cost}</p>
      {item.variants.length > 0 && (
        <div>
          <strong>Variants</strong>
          <ul>
            {item.variants.map((item, index) => (
              <li key={item.id}>
                <h4>{item.name}</h4>
                <p>{item.details}</p>
              </li>
            ))}
          </ul>
        </div>
      )}
    </>
  )

  return (
    <div className="page-content">
      <h1>Morphs</h1>
      
      <p>
        Morphs are the physical forms that your character inhabits. You can transfer your consciousness between morphs through resleeving.
      </p>

      <div className="searchable-container">
        <SearchableList
          items={MORPHS_DATA}
          searchFields={['name', 'description', 'type']}
          onSelect={setSelectedMorph}
          selectedItem={selectedMorph}
          renderDetails={renderDetails}
        />
      </div>
    </div>
  )
}
