import { useState } from 'react'
import SearchableList from '../components/SearchableList'

const MORPHS_DATA = [
  {
    id: 1,
    name: 'Flats',
    type: 'Biomorph',
    description: 'Flats are baseline unmodified humans, born with all of the natural defects',
    details: 'Flats are baseline unmodified humans, born with all of the natural defects, hereditary diseases, and other genetic mutations that evolution so lovingly applies. Flats are increasingly rare—most died off with the rest of humanity during the Fall. Most new children are splicers—screened and genefixed at the least—except in habitats where flats are treated as second-class citizens and indentured labor.',
    implants: 'None',
    aptitude_max: '20',
    durability: '30',
    wound_threshold: '6',
    advantages: '',
    disadvantages: 'None (Genetic Defects trait common)',
    cp_cost: '0',
    credit_cost: 'High',
  },
  {
    id: 2,
    name: 'Splicers',
    type: 'Biomorph',
    description: 'Splicers are genefixed humans.',
    details: 'Splicers are genefixed humans. Their genome has been cleansed of hereditary diseases and optimized for looks and health, but has not otherwise been substantially upgraded. Splicers make up the majority of transhumanity.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '10',
    credit_cost: 'High',
  },
  {
    id: 3,
    name: 'Exalts',
    type: 'Biomorph',
    description: 'Exalt morphs are genetically enhanced humans',
    details: 'Exalt morphs are genetically enhanced humans, designed to emphasize specific traits. Their genetic code has been tweaked to make them healthier, smarter, and more attractive. Their metabolism is modified to predispose them towards staying fit and athletic for the duration of an extended lifespan.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COG, +5 to three other aptitudes of the player\'s choice',
    disadvantages: '',
    cp_cost: '30',
    credit_cost: 'Expensive',
  },
  {
    id: 4,
    name: 'Mentons',
    type: 'Biomorph',
    description: 'Mentons are genetically modified to increase cognitive abilities',
    details: 'Mentons are genetically modified to increase cognitive abilities, particularly learning ability, creativity, attentiveness, and memory. Rumors exist of super- enhanced mentons with more extreme intelligence mods, but brain-hacking is notoriously difficult, and many attempts to redesign mental faculties result in impaired functioning, instability, or insanity.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Eidetic Memory, Hyper Linguist, Math Boost',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+10 COG, +5 INT, +5 WIL, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
  },
  {
    id: 5,
    name: 'Olympians',
    type: 'Biomorph',
    description: 'Olympians are human upgrades with improved athletic capabilities',
    details: 'Olympians are human upgrades with improved athletic capabilities like endurance, eye-hand coordination, and cardiovascular functions. Olympians are common among athletes, dancers, freerunners, and soldiers.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '+5 COO, +5 REF, +10 SOM, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
  },
  {
    id: 6,
    name: 'Slyphs',
    type: 'Biomorph',
    description: 'Slyph morphs are tailor-made for media icons',
    details: 'Slyph morphs are tailor-made for media icons, elite socialites, XP stars, models, and narcissists. Slyph gene sequences are specifically designed for distinctive good looks. Ethereal and elfin features are common, with slim and lithe bodies. Their metabolism has also been sanitized to eliminate unpleasant bodily odors and their pheromones adjusted for universal appeal.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Enhanced Pheromones',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Striking Looks (Level 1) trait, +5 COO, +10 SAV, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
  },
  {
    id: 7,
    name: 'Bouncers',
    type: 'Biomorph',
    description: 'Bouncers are humans genetically adapted for zero-g',
    details: 'Bouncers are humans genetically adapted for zero-g and microgravity environments. Their legs are more limber, and their feet can grasp as well as their hands.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Grip Pads, Oxygen Reserve, Prehensile Feet',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: 'Limber (Level 1) trait, +5 COO, +5 SOM, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive',
  },
  {
    id: 8,
    name: 'Furies',
    type: 'Biomorph',
    description: 'Furies are combat morphs.',
    details: 'Furies are combat morphs. These transgenic human upgrades feature genetics tailored for endurance, strength, and reflexes, as well as behavioral modifications for aggressiveness and cunning. To offset tendencies for unruliness and macho behavior patterns, furies feature gene sequences promoting pack mentalities and cooperation, and they tend to be biologically female.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Bioweave Armor (Light), Cortical Stack, Enhanced Vision, Neurachem (Level 1), Toxin Filters',
    aptitude_max: '30',
    durability: '50',
    wound_threshold: '10',
    advantages: '+5 COO, +5 REF, +10 SOM, +5 WIL, +5 to one aptitude of the player\'s choice. Speed Modifier: +1 (neurachem)',
    disadvantages: '',
    cp_cost: '75',
    credit_cost: 'Expensive (minimum 40,000)',
  },
  {
    id: 9,
    name: 'Futuras',
    type: 'Biomorph',
    description: 'An exalt variant, futura morphs were specially crafted for the “Lost generation.”',
    details: 'An exalt variant, futura morphs were specially crafted for the “Lost generation.” Tailor-made for accelerated growth and adjusted for confidence, self-reliance, and adaptability, futuras were intended to help transhumanity regain its foothold. These programs proved disastrous and the line was discontinued, but some models remain, viewed by some with distaste and others as collectibles or exotic oddities.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Eidetic Memory, Emotional Dampers',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 COG, +5 SAV, +10 WIL, +5 to one other aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '40',
    credit_cost: 'Expensive (exceptionally rare; 50,000+)',
  },
  {
    id: 10,
    name: 'Ghosts',
    type: 'Biomorph',
    description: 'Ghosts are partially designed for combat applications, but their primary focus is stealth and infiltration.',
    details: 'Ghosts are partially designed for combat applications, but their primary focus is stealth and infiltration. Their genetic profile encourages speed, agility, and reflexes, and their minds are modified for patience and problem-solving.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Chameleon Skin, Cortical Stack, Adrenal Boost, Enhanced Vision, Grip Pads',
    aptitude_max: '30',
    durability: '45',
    wound_threshold: '9',
    advantages: '+10 COO, +5 REF, +5 SOM, +5 WIL, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '70',
    credit_cost: 'Expensive (minimum 40,000)',
  },
  {
    id: 11,
    name: 'Hibernoids',
    type: 'Biomorph',
    description: 'Hibernoids are transgenic-modified humans with heavily altered sleep patterns and metabolic processes.',
    details: 'Hibernoids are transgenic-modified humans with heavily altered sleep patterns and metabolic processes. Hibernoids have a decreased need for sleep, requiring only 1–2 hours a day on average. They also have the ability to trigger a form of voluntary hibernation, effectively stopping their metabolism and need for oxygen. Hibernoids make excellent long-duration space travelers and habtechs, but these morphs are also favored by personal aides and hypercapitalists with non-stop lifestyles.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Circadian Regulation, Cortical Stack, Hibernation',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 INT, +5 to one aptitude of the player\'s choice',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
  },
  {
    id: 12,
    name: 'Neotenics',
    type: 'Biomorph',
    description: 'Neotenics are transhumans modified to retain a child-like form.',
    details: 'Neotenics are transhumans modified to retain a child-like form. They are smaller, more agile, inquisitive, and less resource-depleting, making them ideal for habitat living and spacecraft. Some people find neotenic sleeves distasteful, especially when employed in certain media and sex work capacities.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '20 (SOM), 30 (all else)',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 COO, +5 INT, +5 REF, +5 to one aptitude of the player\'s choice; neotenics count as a small target (-10 modifier to hit in combat)',
    disadvantages: 'Social Stigma (Neotenic) trait',
    cp_cost: '25',
    credit_cost: 'Expensive',
  },
  {
    id: 13,
    name: 'Remade',
    type: 'Biomorph',
    description: 'The remade are completely redesigned humans: humans 2.0.',
    details: 'The remade are completely redesigned humans: humans 2.0. Their cardiovascular systems are stronger, the digestive tract has been sanitized and restructured to eliminate flaws, and they have otherwise been optimized for good health, smarts, and longevity with numerous transgenic mods. The remade are popular with the ultimates faction. The remade look close to human, but are different in very noticeable and sometimes eerie ways: taller, lack of hair, slightly larger craniums, wider eyes, smaller noses, smaller teeth, and elongated digits.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Circadian Regulation, Clean Metabolism, Cortical Stack, Eidetic Memory, Enhanced Respiration, Temperature Tolerance, Toxin Filters',
    aptitude_max: '40',
    durability: '40',
    wound_threshold: '8',
    advantages: '+10 COG, +5 SAV, +10 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: 'Uncanny Valley trait',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 40,000+)',
  },
  {
    id: 14,
    name: 'Rusters',
    type: 'Biomorph',
    description: 'Adapted for survival with minimum gear in the not-yet-terraformed Martian environment',
    details: 'Adapted for survival with minimum gear in the not-yet-terraformed Martian environment, these transgenic morphs feature insulated skin for more effective thermoregulation and respiratory system improvements to require less oxygen and filter carbon dioxyde, among other mods.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Enhanced Respiration, Temperature Tolerance',
    aptitude_max: '25',
    durability: '35',
    wound_threshold: '7',
    advantages: '+5 SOM, +5 to one aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
  },
  {
    id: 15,
    name: 'Neo-Avians',
    type: 'Biomorph',
    description: 'Neo-avians include ravens, crows, and gray parrots uplifted to human-level intelligence.',
    details: 'Neo-avians include ravens, crows, and gray parrots uplifted to human-level intelligence. Their physical sizes are much larger than their non-uplifted cousins (to the size of a human child), with larger heads for their increased brain size. Numerous transgenic modifica- tions have been made to their wings, allowing them to retain limited flight capabilities at 1 g, but giving them a more bat-like physiology so they can bend and fold better and adding primitive digits for basic tool manipulation. Their toes are also more articulated and now accompanied with an opposable thumb. Neo-avians have adapted well to microgravity environments, and are favored for their small size and reduced resource use.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack',
    aptitude_max: '25 (20 SOM)',
    durability: '20',
    wound_threshold: '4',
    advantages: 'Beak/Claw Attack (1d10 DV, -1, use Unarmed Combat skill), Flight, +5 INT, +10 REF, +5 to one other aptitude of the player’s choice. Neo-avians count as a small target (-10 modifier to hit in combat).',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
  },
  {
    id: 16,
    name: 'Neo-Hominids',
    type: 'Biomorph',
    description: 'Neo-hominids are uplifted chimpanzees, gorillas, and orangutans.',
    details: 'Neo-hominids are uplifted chimpanzees, gorillas, and orangutans. All feature enhanced intelligence and bipedal frames.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Prehensile Feet',
    aptitude_max: '25',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 COO, +5 INT, +5 SOM, +5 to one other aptitude of the player’s choice, +10 Climbing skill',
    disadvantages: '',
    cp_cost: '25',
    credit_cost: 'Expensive',
  },
  {
    id: 17,
    name: 'Octomorphs',
    type: 'Biomorph',
    description: '',
    details: 'These uplifted octopi sleeves have proven quite useful in zero-gravity environments. They retain eight arms, their chameleon ability to change skin color, ink sacs, and a sharp beak. They also have increased brain mass and longevity, can breathe both air and water, and lack a skeletal structure so they can squeeze through tight spaces. Octomorphs typically crawl along in zero gravity using their arm suckers and expelling air for propulsion and can even walk on two of their arms in low gravity. Their eyes have been enhanced with color vision, provide a 360-degree field of vision, and rotationally adjust to keep the slit-shaped pupil aligned with “up.” A transgenic vocal system allows them to speak.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Chameleon Skin',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '8 Arms, Beak Attack (1d10 DV, AP -1, use Unarmed Combat skill), Ink Attack (blinding, use Exotic Ranged: Ink Attack skill), Limber (Level 2) trait, 360-degree Vision, +30 Swimming skill, +10 Climbing skill, +5 COO, +5 INT, +5 to one other aptitude of the player’s choice',
    disadvantages: '',
    cp_cost: '50',
    credit_cost: 'Expensive (minimum 30,000+)',
  },
  {
    id: 18,
    name: 'Pleasure Pods',
    type: 'Pods',
    description: 'Pleasure pods are exactly what they seem: faux humans designed purely for intimate entertainment purposes.',
    details: 'Pleasure pods are exactly what they seem: faux humans designed purely for intimate entertainment purposes. Pleasure pods have extra nerve clusters in their erogenous zones, fine motor control over certain muscle groups, enhanced pheromones, sanitized metabolisms, and the genetics for purring. Naturally, they are crafted for good looks and charisma and enhanced in other areas as well. Pleasure pods are capable of switching their sex at will to male, female, hermaphrodite, neuter, or other intersex variations.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Cyberbrain, Enhanced Pheromones, Mnemonic Augmentation, Puppet Sock, Sex Switch',
    aptitude_max: '30',
    durability: '30',
    wound_threshold: '6',
    advantages: '+5 INT, +5 SAV, +5 to one aptitude of the player’s choice',
    disadvantages: 'Social Stigma (Pleasure Pod) trait',
    cp_cost: '20',
    credit_cost: 'High',
  },
  {
    id: 19,
    name: 'Worker Pods',
    type: 'Pods',
    description: 'Part exalt human, part machine',
    details: 'Part exalt human, part machine, these basic pods are virtually indistinguishable from humans. Worker pods are often used in menial labor jobs where interaction with humans is necessary.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Cortical Stack, Cyberbrain, Mnemonic Augmentation, Puppet Sock',
    aptitude_max: '30',
    durability: '35',
    wound_threshold: '7',
    advantages: '+10 SOM, +5 to one aptitude of the player’s choice',
    disadvantages: 'Social Stigma (Pod) trait',
    cp_cost: '20',
    credit_cost: 'High',
  },
  {
    id: 20,
    name: 'Novacrab',
    type: 'Pods',
    description: 'Novacrabs are a pod design bioengineered from coconut crab and spider crab stock',
    details: 'Novacrabs are a pod design bioengineered from coconut crab and spider crab stock and grown to a larger (human) size. Novacrabs are ideal for hazardous work environments as well as vacworker, police, or bodyguard duties, given their ten 2-meter long legs, massive claws, and chitinous armor. They climb and handle microgravity well and can withstand a wide range of atmospheric pressure (and sudden pressure changes) from vacuum to deep sea. Novacrabs feature compound eyes (with human-equivalent image resolution), gills, dexterous manipulatory digits on their fifth set of limbs, and transgenic vocal cords.',
    implants: 'Basic Biomods, Basic Mesh Inserts, Carapace Armor, Cortical Stack, Cyberbrain, Enhanced Respiration, Gills, Mnemonic Augmentation, Oxygen Reserve, Puppet Sock, Temperature Tolerance, Vacuum Sealing',
    aptitude_max: '30',
    durability: '40',
    wound_threshold: '8',
    advantages: '10 legs, Carapace Armor (11/11), Claw Attack (DV 2d10), +10 SOM, +5 to two other aptitudes of the player’s choice',
    disadvantages: '',
    cp_cost: '60',
    credit_cost: 'Expensive (minimum 30,000+)',
  },



  {
    id: 21,
    name: '',
    type: 'Synthetic Morph',
    description: '',
    details: '',
    implants: '',
    aptitude_max: '',
    durability: '',
    wound_threshold: '',
    advantages: '',
    disadvantages: '',
    cp_cost: '',
    credit_cost: '',
  },
]

export default function Morphs() {
  const [selectedMorph, setSelectedMorph] = useState(null)

  const renderDetails = (item) => (
    <>
      <h3>{item.name}</h3>
      <p>{item.details}</p>
      <p><strong>Type:</strong> {item.type}</p>
      <p><strong>Implants:</strong> {item.implants}</p>
      <p><strong>Aptitude Maximum:</strong> {item.aptitude_max}</p>
      <p><strong>Durability:</strong> {item.durability}</p>
      <p><strong>Wound Threshold:</strong> {item.wound_threshold}</p>
      <p><strong>Advantages:</strong> {item.advantages}</p>
      <p><strong>Disadvantages:</strong> {item.disadvantages}</p>
      <p><strong>CP Cost:</strong> {item.cp_cost}</p>
      <p><strong>Credit Cost:</strong> {item.credit_cost}</p>
      
    </>
  )

  return (
    <div className="page-content">
      <h1>Morphs</h1>
      
      <p>
        Morphs are the physical forms that your character inhabits. You can transfer your consciousness between morphs through resleeving.
      </p>

      <div className="searchable-container">
        <SearchableList
          items={MORPHS_DATA}
          searchFields={['name', 'description', 'type']}
          onSelect={setSelectedMorph}
          selectedItem={selectedMorph}
          renderDetails={renderDetails}
        />
      </div>
    </div>
  )
}
